# Generated by Django 4.2.9 on 2024-11-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('sku', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
