# Generated by Django 4.2.9 on 2024-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='BuyerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='Country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='Product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='PurchaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
