# Generated by Django 4.2.9 on 2024-11-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Productss',
            field=models.TextField(blank=True, null=True),
        ),
    ]
