# Generated by Django 4.2.9 on 2024-11-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_sales_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='path',
            field=models.URLField(default='http://default.url'),
        ),
    ]
