# Generated by Django 4.2.9 on 2024-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sales_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='path',
            field=models.URLField(default='F:\\App_Shower_Doors\\media\x06\\mom-with-baby-in-her-belly-waiting-for-the-birth-free-vector.jpg'),
        ),
    ]
