# Generated by Django 4.2.9 on 2024-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_sales_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='path',
            field=models.URLField(),
        ),
    ]
