# Generated by Django 4.2.9 on 2024-11-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_sales_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='path',
        ),
    ]
