# Generated by Django 4.2.9 on 2024-11-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_sales_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Product Image'),
        ),
    ]
